version: '3.9'

services:
  # 代理
  mitm:
    image: ethanwang9/proxy_pool_mitm:1.0.0
    container_name: ProxyPool-Mitm
    build:
      context: ./mitm
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "23456:23456"
    depends_on:
      - pool
    environment:
      - PROXY_PORT=23457
    networks:
      - network

  # 爬虫
  pool:
    image: ethanwang9/proxy_pool_pool:1.0.0
    container_name: ProxyPool-Pool
    build:
      context: ./pool
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "23457:23457"
    depends_on:
      - redis
    environment:
      - RUN_PORT=23457
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=GnnIHXynF4Dqft2s
    networks:
      - network

  # 数据库 Redis
  redis:
    image: redis:latest
    container_name: ProxyPool-Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: --requirepass "GnnIHXynF4Dqft2s"
    networks:
      - network

#挂在容器卷
volumes:
  redis_data:

# 网络
networks:
  network:
    