version: '3'

services:
  # 代理
  mitm:
    image: ethanwang9/proxy_pool_mitm:1.0.0
    container_name: ProxyPool-Mitm
    build:
      context: ./mitm
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "23456:23456"
    depends_on:
      - pool
    environment:
      - PROXY_ADDR=192.168.0.11:23457
    networks:
      network:
        ipv4_address: 192.168.0.10

  # 爬虫
  pool:
    image: ethanwang9/proxy_pool_pool:1.0.0
    container_name: ProxyPool-Pool
    build:
      context: ./pool
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "23457:23457"
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=192.168.0.12
      - REDIS_PASSWORD=GnnIHXynF4Dqft2s
    networks:
      network:
        ipv4_address: 192.168.0.11

  # 数据库 Redis
  redis:
    image: redis:latest
    container_name: ProxyPool-Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: --requirepass "GnnIHXynF4Dqft2s"
    networks:
      network:
        ipv4_address: 192.168.0.12

#挂在容器卷
volumes:
  redis_data:

# 网络
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: '192.168.0.1/24'